tpos: device-tree: remove double code in compound_slave()
WRONG, WRONG, WRONG: by last merge with Xilinx code I have
insert double code -- add empty ranges. So we get errors:

DTC: dts->dtb  on file "arch/microblaze/boot/dts/test.dts"
ERROR (duplicate_property_names): Duplicate property name ranges in /plb@0/xps-ll-temac@88f00000
ERROR: Input tree has errors, aborting (use -f to force output)

this is a fix

Signed-off-by: Stephan Linz <linz@li-pro.net>